services:
  zl_chain:
    build:
      context: ./zl_chain
      dockerfile: Dockerfile
    command: cargo run
    ports:
      - "8545:8545"
    volumes:
      - ./config/ptp4l.conf:/etc/ptp4l.conf

  data_ingest:
    build:
      context: ./data_ingest
      dockerfile: Dockerfile

  ai_preprocess:
    build:
      context: ./ai_preprocess
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - RAW_TICKS_TOPIC=rawticks
      - SENTIMENT_TOPIC=sentiment

  strategy_engine:
    build:
      context: ./strategy_engine
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_ADDR=redis:6379
      - SENTIMENT_TOPIC=sentiment
      - ORDERS_TOPIC=orders

  matching_engine:
    build:
      context: ./matching_engine
      dockerfile: Dockerfile
    # removed explicit command to use Dockerfile CMD

  execution_api:
    build:
      context: ./execution_api
      dockerfile: Dockerfile
    command: go run src/api.go
    ports:
      - "8080:8080"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - SENTIMENT_TOPIC=sentiment
      - ORDERS_TOPIC=orders
      - EXECUTION_API_HOST=execution_api:8080
    depends_on:
      - kafka
      - execution_api
    ports:
      - "3000:3000"

  redis:
    image: redis:7.0

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

networks:
  default:
    driver: bridge
